In [1]:
import numpy as np

In [5]:
arr_1D = np.array([1,2,3,4])
print(arr_1D)

[1 2 3 4]


In [6]:
type(arr_1D)

numpy.ndarray

In [7]:
arr_1D.ndim #Tells the dimension of our array

1

In [8]:
arr_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2D)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr_2D.ndim 

2

In [12]:
arr_1D.size #Tells the size of array i.e no. of elements present in total

4

In [13]:
arr_2D.size

8

In [15]:
arr_2D.shape  #(row, column)

(2, 4)

In [16]:
arr_2D.dtype # type of data present inside the array

dtype('int32')

In [18]:
matrix = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [22]:
matrix_1s = np.ones(5) #to create 1's matrix directly of desired size (row,column), if only on no. provided in argument then it takes default row as 1
print(matrix_1s)

[1. 1. 1. 1. 1.]


In [25]:
matrix_1s = np.ones((3,4)) # here we get default data type as float
print(matrix_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# to get matrix of desired data type 
# to get what all arguments the function takes press = Shift + Tab
matrix_1s = np.ones((3,4), dtype= int) 
print(matrix_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [30]:
# for default values as 0 in matrix
matrix_0s = np.zeros((4,6))
print(matrix_0s)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [39]:
matrix_0s_bool = np.zeros((4,6), dtype = bool)
print(matrix_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [40]:
matrix_0s_str = np.zeros((4,6), dtype = str)
print(matrix_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [41]:
empty_str = ()
print(bool(empty_str))

False


In [48]:
# Creating emoty matrix, though it will contain random values wrt the dtype provided
empty_matrix = np.empty((3,3))
print(empty_matrix) 

[[1.06137876e-312 0.00000000e+000 1.06395697e+224]
 [3.34273129e-061 1.74659601e-076 1.18672405e-075]
 [2.78870515e+179 4.46389766e-086 6.27207943e-310]]
